# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce5b1b7c7cdd2e1e6df1d0c346a0ed1cc469cf9b13e7d08a1343bacb2f5bdf307e066dbc8cd8af495664d279a0a5ef2bc0ae69299a2dae86e9cd826b6d5bd1d0

test:
  secret_key_base: c06d2b628141f6919dcdfc463d03aec02006731020d4bf82e0b104c751ef4f7e360ba8aadf40b07c9c6effc114805549c2f19ca1b11606deb776ea1f146a7644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
